### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gokulesh2001**
A small typo error was corrected.

### CODE REVIEW

**Comment by vengadeshks** [comment]
I have changed myself

**Comment by Gokulesh2001** [comment]
No problem bro!!

**Comment by vengadeshks** [comment]
Always online in coding platforms which grows you ahead and ahead bro!!

**Comment by Gokulesh2001** [comment]
I am not online. I am just getting mails bro!

**Comment by vengadeshks** [comment]
That's what I am saying you guys always checking mail right?

**Comment by Gokulesh2001** [comment]
I don't need to check bro.. Notification comes!

**Pull request closed without merging**
